- name: docker inpsect on all nodes
  hosts: all
  gather_facts: True
  tasks:
   - name: testing connectivity to all nodes
     ping: 
   - name: Checking docker service on all nodes
     service:
       name: docker
       state: started
   - name: checking for the registry container
     docker_container:
       name: xreg.1.8d12wqefy7zsm1eewh8pfpvv0
       state: present
       image: registry:lot
