- name: debug module for *
  hosts: node3
  tasks:
    - name: capture output of * command
      raw: "docker container ls |grep xreg" 
      register: output
   
    - debug: msg="***ERROR NO REGISTRY CONTAINER DETECTED"
      when: output.stdout.find('xreg') != 1 
