- name: debug module for *
  hosts: node3
  tasks:
    - name: capture output of * command
      raw: "docker container ls |grep xreg" 
      register: output
   
    - debug: msg="Container Xreg DETECTED"
      when: output.stdout.find('xreg') != -1

    - debug: msg="Container NO Xreg DETECTED"
      when: output.stdout == ""
