- name: Example for a nsible delegate
  hosts: walkr
  gather_facts: false
  tasks:
  - raw: touch /tp/dhoom.txt
    notify: web_terminate

  handlers: 
  - name: web_terminate
    raw: shutdown -h now
    delegate_to: web