- name: dkcker imspect all nodoa
  hosts: all
  gather_facts: false
  tasks:
   - name: testing connectivity
     ping:
   - name: checking docker service
     service:
       name: docker
       state: started
