- name: prune everything
  hosts: walkr
  gather_facts: false
  tasks:
  - name: pruning containers
    shell: docker container prune -f
  - name: pruning volumes
    shell: docker volume prune -f
  - name: pruning images
    shell: docker image rm -f $(docker image ls -a -q) 
  - name: pruning networks
    shell: docker network prune -f
