- name: prune everything
  hosts: walkr
  gather_facts: false
  tasks:
  - name: pruning containers
    shell: docker container prune
  - name: pruning volumes
    shell: docker volume prune
  - name: pruning images
    shell: docker image prune
  - name: pruning networks
    shell: docker network prune
