- name: prune everything
  hosts: all
  gather_facts: false
  tasks:
  - name: pruning containers
    command: docker container prune
  - name: pruning images
    command: docker image prune
  - name: pruning volumes
    command: docker volume prune