- name: Preparing to stop docker
  hosts: all
  gather_facts: true
  tasks:
  - name: Stop the docker service 
    service: name=docker state=stopped
  
- name: Shutting workers down
  hosts: walkr*
  gather_facts: false
  tasks:
  - raw: shutdown -h now
    notify: self_terminate

  handlers: 
  - name: sef_terminate
    raw: shutdown -h now
    delegate_to: 127.0.0.1

 
