- name: Preparing to stop docker
  hosts: all
  gather_facts: true
  tasks:
  - name: Stop the docker service 
    service: name=docker state=stopped
  
- name: Shutting workers down
  hosts: walkr
  gather_facts: false
  tasks:
  - raw: shutdown -h now
    notify: shutdown_xter  

  handlers:
  - name: shutdown_xter 
    hosts: xter
    raw: shutdown -h now
 
