- name: Shutting down walkr
  hosts: all
  gather_facts: true
  tasks:
  - name: Stop the docker service 
    service: name=docker state=stopped
    notify: shutdown_walkr
 
  handlers:
  - name: shutdown_walkr nodes
    raw: shutdown -h now
    when: ansible_hostname != "xter"
  - name: shutdown_xter
    raw: shutdown_h now 
