- name: checking network connectivity and for docker service
  hosts: all
  gather_facts: true
  tasks:
  - name: Pinging all nodes
    ping:
  - name: Checking for latest docker package
    yum: name=docker-ce state=latest
    notify: restart_docker
  - name: Check for docker service
    service: name=docker state=started
  handlers:
    restart_docker:
    service: name=docker state=restarted
- include: Xreg_check.yml


  
