- name: Checking for Registry
  hosts: x
  tasks:
    - name: CHECKING FOR LOCAL DOCKER REGISTRY
      raw: "docker container ls |grep xreg" 
      register: output
      ignore_errors: True
   
    - debug: msg="Container Xreg DETECTED"
      when: output.stdout.find('xreg') != -1

    - debug: msg="FATAL   ***NO REGISTRY CONTAINER DETECTED*** "
      when: output.stdout == ""