- name: Cleaning previous swarm settings
  hosts: all
  tasks:
  - raw: docker swarm leave -f
    ignore_errors: yes

- name: Swarm - Initiating the manager node on xter
  hosts: x
  gather_facts: no
  tasks:
  - raw: docker swarm init
    raw: docker swarm join-token -q worker
    register: token 
  
- name: Swarm - Inititating the worker nodes.
  hosts: walkr
  gather_facts: no
  vars:
    tok: "{{ hostvars['xter']['token']['stdout'] }}"
  tasks:
  - debug: "{{ tok }}"
    

