- name: Cleaning previous swarm settings
  hosts: all
  tasks:
  - raw: docker swarm leave -f
    ignore_errors: yes

- name: Swarm - Initiating the manager node on xter
  hosts: x
  tasks:
  - raw: docker swarm init | grep 2377
    register: token 
  
- name: Swarm - Inititating the worker nodes
  hosts: walkr
  tasks:
  - debug: 
    var: "{{ hostvars['xter']['token']['stdout'] }}" 
    

