- name: Cleaning previous swarm settings
  hosts: all
  tasks:
  - raw: docker swarm leave -f
    ignore_errors: yes

- name: Swarm - Initiating the manager node on xter
  hosts: x
  gather_facts: no
  tasks:
  - raw: docker swarm init --advertise-addr 192.168.20.2 | grep 2377
    register: token 
  - debug: var=token.stdout

- name: Swarm - Inititating the worker nodes.
  hosts: walkr
  gather_facts: no
  vars:
    tok: "{{ hostvars.xter.token.stdout.split('\n') }}"
  tasks:
  - debug: var=tok
  - msg: "{{ tok }}" 
 
    

